# API Keys
api_keys:
  openai: "your-openai-api-key"  # GPT models
  anthropic: "your-anthropic-api-key"  # Claude models
  gemini: "your-gemini-api-key"  # Gemini models
  huggingface: "your-huggingface-api-key"  # To download models from HuggingFace

model_path:
  huggingface: "/home/yanglei/Qwen2.5-VL-3B-Instruct"  # directory to store downloaded models

# Dataset
data:
  root: "data/nuscenes"  # Path to nuScenes dataset
  root: "data/v2x-seq-nuscenes/vehicle-side"  # Path to nuScenes dataset
  root: "data/v2x-seq-nuscenes/infrastructure-side"  # Path to nuScenes dataset
  root: "data/v2x-seq-nuscenes/cooperative"  # Path to nuScenes dataset
  version: "v1.0-trainval"  # Dataset version (v1.0-mini, v1.0-trainval, v1.0-test)
  results: "results"  # Directory to store results

# Prediction Parameters (do not change)
prediction:
  obs_len: 6  # Number of past observations (frames)
  fut_len: 6  # Number of future predictions (frames)
  ext_len: 2  # Extra length for calculations (frames)
